### ISSUE TITLE
[BUG] [Pull Request Utils]: Installation on DevOps Server 2020 with erros 

### ISSUE THREAD

**Issue by cfs77** [joachimdalen/AzureDevOpsExtensions#10]
**Describe the bug**
I tryed to install the extension on DevOps Server 2020. The installation failed with an error.

**Screenshots**
![image](https://user-images.githubusercontent.com/37112783/153711670-e54b2c46-007b-4431-861a-3cd5961e4cbe.png)
![image](https://user-images.githubusercontent.com/37112783/153711724-c73c73da-7e65-4c0d-8168-c929fc74e13f.png)

**Comment by joachimdalen** [comment]
Hi! 

Thanks for the report. I'll look into this and get back to you.

**Comment by joachimdalen** [comment]
I've located the issue and working on a fix that will be rolled out in a bit.

**Comment by joachimdalen** [comment]
I released version `0.5.5` that should contain the fixes for your issue. Could you please try to install it again?

**Comment by cfs77** [comment]
Worked for me.  
Thank you for the quick response and fix. :-)
