### ISSUE TITLE
[FEATURE]: Be able to specify pr id when checking tags

### ISSUE THREAD

**Issue by JoeGandy** [joachimdalen/AzureDevOpsExtensions#4]
**Is your feature request related to a problem? Please describe.**
It'd be nice to make the useDefined/pullRequestId parameters consistent across the calls

**Describe the solution you'd like**
useDefined/pullRequestId to be added so we can specify the PR for each action

**Additional context**
N/A

**Comment by joachimdalen** [comment]
Hi!

I do agree that some of the different parameters could more aligned across the tasks. This should not be a change to implement, so I will take a look at it sometime today.

**Comment by joachimdalen** [comment]
Hi again!

I just published some changes (extension version: `0.4.3`) that allows `useDefined` and `pullRequestId` to be used in all tasks.

**Comment by JoeGandy** [comment]
Ah that's awesome news, I'll have a play around with it tomorrow, thanks for grabbing it so quick!

**Comment by joachimdalen** [comment]
No worries, I had the time to do it (and it was a small task). Great to see others getting the use for it! 💯 

I'll leave this issue open a bit more in case you face any issues. Nothing logic wise should have changed, but always good to get a 3rd party test 👍

**Comment by JoeGandy** [comment]
Worked perfectly for our use cases, so nice one :)
