### ISSUE TITLE
[FEATURE]: additional option policy type for PullRequestStatus

### ISSUE THREAD

**Issue by knoxi** [joachimdalen/AzureDevOpsExtensions#9]
**Is your feature request related to a problem? Please describe.**
Currently, new pull request status policies created by `PullRequestStatus` are set as optional policies.

**Describe the solution you'd like**
Please provide an additional option for `PullRequestStatus` where the policy type can be set to `Optional` or `Required`.

**Additional context**
-

**Comment by joachimdalen** [comment]
Hi!

If a status should be optional or required is not actually controlled by the status itself, so I am unable to set this from the task. To make a status required, you have to configure a branch policy and set it to required there.

See this for more info: https://docs.microsoft.com/en-us/azure/devops/repos/git/pr-status-policy?view=azure-devops#configure-the-branch-policy

**Comment by knoxi** [comment]
Thanks for the explanation, too bad the api does not allow this.
